language: java
jdk:
- oraclejdk8
script:
- ./gradlew build -i
deploy:
  skip_cleanup: true
  provider: script
  script: deploy/nexus.sh
  on:
    tags: true
    all_branches: true
addons:
  chrome: beta

sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_76d841558dc7_key -iv $encrypted_76d841558dc7_iv
  -in deploy/private.gpg.enc -out deploy/private.gpg -d
